name: Setup Node.js
description: "This action sets up Node.js"
inputs:
  node-version:
    description: "The Node.js version to use"
    required: true
    default: "16.x"
runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}
