name: Chroma Python Stress Tests

on:
  workflow_call:
    inputs:
      python_versions:
        description: 'Python versions to test (as json array)'
        required: false
        default: '["3.8"]'
        type: string


jobs:
  stress-test:
    timeout-minutes: 90
    strategy:
      matrix:
        python: ${{fromJson(inputs.python_versions)}}
        platform: ['16core-64gb-ubuntu-latest', '16core-64gb-windows-latest']
        testfile: ["'chromadb/test/stress/'"]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python }}
    - name: Install test dependencies
      run: python -m pip install -r requirements.txt && python -m pip install -r requirements_dev.txt
    - name: Upgrade SQLite
      run: python bin/windows_upgrade_sqlite.py
      if: runner.os == 'Windows'
    - name: Test
      run: python -m pytest ${{ matrix.testfile }}
