name: Lint
description: This lints using pre-commit.
runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v4
    - name: Install pre-commit
      shell: bash
      run: python -m pip install -r requirements_dev.txt
    - name: Run pre-commit
      shell: bash
      run: |
        pre-commit run --all-files trailing-whitespace
        pre-commit run --all-files mixed-line-ending
        pre-commit run --all-files end-of-file-fixer
        pre-commit run --all-files requirements-txt-fixer
        pre-commit run --all-files check-xml
        pre-commit run --all-files check-merge-conflict
        pre-commit run --all-files check-case-conflict
        pre-commit run --all-files check-docstring-first
        pre-commit run --all-files black
        pre-commit run --all-files flake8
        pre-commit run --all-files prettier
        pre-commit run --all-files check-yaml
