name: Run Python tests
description: This runs Python tests using pytest given file glob(s) to run.
inputs:
  python-version:
    description: "Python version to test"
    required: false
    default: "3.8"
  test-globs:
    description: "Globs to use for testing"
    required: true
runs:
  using: "composite"
  steps:
    - name: Setup
      uses: ./.github/actions/python
      with:
        python-version: ${{ inputs.python-version }}
    - name: Test
      run: python -m pytest ${{ inputs.test-globs }}
      shell: bash
