name: Python client tests

on:
  workflow_call:
    inputs:
      python_versions:
        description: 'Python versions to test (as json array)'
        required: false
        default: '["3.8"]'
        type: string

jobs:
  test:
    strategy:
      matrix:
        python: ${{fromJson(inputs.python_versions)}}
        platform: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup
        uses: ./.github/actions/python
        with:
          python-version: ${{ matrix.python }}
      - name: Test
        run: clients/python/integration-test.sh
