name: Chroma Python Stress Tests

on:
  workflow_call:
    inputs:
      python_versions:
        description: 'Python versions to test (as json array)'
        required: false
        default: '["3.8"]'
        type: string


jobs:
  stress-test:
    timeout-minutes: 90
    strategy:
      matrix:
        python: ${{fromJson(inputs.python_versions)}}
        platform: ['16core-64gb-ubuntu-latest', '16core-64gb-windows-latest']
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3
      - uses: ./actions/python-test
        with:
          python-version: ${{ matrix.python }}
          test-globs: "chromadb/test/stress/"
