name: SSH Debug

on:
 push:
    branches:
      - beggers/fix-auth-overwrite

jobs:
  debug:
    strategy:
        matrix:
          python: ['3.10']
          platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup upterm session
      uses: lhotari/action-upterm@v1